name: DEPLOYMENT
on: [push]
jobs:
  LINT-ALL:
    name: LINTER - An치lise de c칩digo est치tico
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1

      - name: Node Install
        run: npm install

      - name: ESLint
        run: npm run lint

      - name: Lint/SASS
        run: npm run lint:sass

  BUILD:
    name: BUILDER - Gerando Execut치vel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1

      - name: Node Install
        run: npm install

      - name: Build
        run: npm run build:core
